services:
  api-gateway:
    build: .
    container_name: api-gateway
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - internal
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-api-gateway
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: api_gateway_db
      MYSQL_USER: api_gateway_user
      MYSQL_PASSWORD: api_gateway_pass
    volumes:
      - mysql_gateway_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - internal

volumes:
  mysql_gateway_data:

networks:
  internal:
    driver: bridge
