#C:\Repos\Laravel-Microservices\docker-compose.yml
services:
  # Redis condiviso
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - internal
      # - net-redis-analytics-service
      # - net-redis-api-gateway
      # - net-redis-jwt-service
      # - net-redis-catalog-service
      # #- net-redis-frontend
      # - net-redis-notification-service
      # - net-redis-order-service
      # - net-redis-payment-service
      # - net-redis-user-service

  # RabbitMQ condiviso
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal
      # - net-rabbitmq-analytics-service
      # - net-rabbitmq-jwt-service
      # - net-rabbitmq-catalog-service
      # #- net-rabbitmq-frontend
      # - net-rabbitmq-notification-service
      # - net-rabbitmq-order-service
      # - net-rabbitmq-payment-service
      # - net-rabbitmq-user-service
                             
  sql-server:                                             # database MySQL dedicato
    image: mcr.microsoft.com/mssql/server:2019-latest     # immagine MySQL 8.x ufficiale
    container_name: sql-server                            # nome fisso del container DB
    restart: unless-stopped                               # riavvia dopo crash, ma non se fermato a mano
    environment:                                          # credenziali/database da creare al primo avvio
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: rootpass
    volumes:
      - sql-server-data:/var/opt/mssql
    networks:
      - internal
      # - net-sql-server-analytics-service
      # - net-sql-server-jwt-service
      # - net-sql-server-catalog-service
      # - net-sql-server-notification-service
      # - net-sql-server-order-service
      # - net-sql-server-payment-service
      # - net-sql-server-user-service

volumes:
  redis_data:
  rabbitmq_data:
  sql-server-data:

networks:
  internal:
  # # redis <-> each service
  # net-redis-analytics-service:           { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.101.0/24" } ] } }
  # net-redis-api-gateway:                 { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.102.0/24" } ] } }
  # net-redis-jwt-service:                { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.103.0/24" } ] } }
  # net-redis-catalog-service:             { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.104.0/24" } ] } }
  # #net-redis-frontend:                   { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.105.0/24" } ] } }
  # net-redis-notification-service:        { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.106.0/24" } ] } }
  # net-redis-order-service:               { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.107.0/24" } ] } }
  # net-redis-payment-service:             { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.108.0/24" } ] } }
  # net-redis-user-service:                { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.109.0/24" } ] } }

  # # rabbitmq <-> each service            
  # net-rabbitmq-analytics-service:        { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.111.0/24" } ] } }
  # net-rabbitmq-jwt-service:             { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.112.0/24" } ] } }
  # net-rabbitmq-catalog-service:          { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.113.0/24" } ] } }
  # #net-rabbitmq-frontend:                { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.114.0/24" } ] } }
  # net-rabbitmq-notification-service:     { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.115.0/24" } ] } }
  # net-rabbitmq-order-service:            { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.116.0/24" } ] } }
  # net-rabbitmq-payment-service:          { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.117.0/24" } ] } }
  # net-rabbitmq-user-service:             { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.118.0/24" } ] } }
  
  # # sql-server <-> each service          
  # net-sql-server-analytics-service:      { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.121.0/24" } ] } }
  # net-sql-server-jwt-service:           { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.122.0/24" } ] } }
  # net-sql-server-catalog-service:        { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.123.0/24" } ] } }
  # net-sql-server-notification-service:   { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.124.0/24" } ] } }
  # net-sql-server-order-service:          { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.125.0/24" } ] } }
  # net-sql-server-payment-service:        { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.126.0/24" } ] } }
  # net-sql-server-user-service:           { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.127.0/24" } ] } }

  # # api-gateway <-> each service
  # net-api-gateway-analytics-service:     { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.131.0/24" } ] } }
  # net-api-gateway-jwt-service:          { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.132.0/24" } ] } }
  # net-api-gateway-catalog-service:       { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.133.0/24" } ] } }
  # #net-api-gateway-frontend:             { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.134.0/24" } ] } }
  # net-api-gateway-notification-service:  { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.135.0/24" } ] } }
  # net-api-gateway-order-service:         { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.136.0/24" } ] } }
  # net-api-gateway-payment-service:       { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.137.0/24" } ] } }
  # net-api-gateway-user-service:          { driver: bridge, ipam: { driver: default, config: [ { subnet: "172.18.138.0/24" } ] } }