#C:\Repos\laravel-microservices\docker-compose.mgmt.yml
services:
  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
    ports:
      - "1433:1433"
      - "1434:1434"

  # zookeeper:
  #   ports:
  #     - "2181:2181"

  kafka:
    ports:
      - "9092:9092"
