#C:\Repos\Laravel-Microservices\docker-compose.yml
services:
  # Redis condiviso
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - net-redis-analytics-service
      - net-redis-api-gateway
      - net-redis-auth-service
      - net-redis-catalog-service
      #- net-redis-frontend
      - net-redis-notification-service
      - net-redis-order-service
      - net-redis-payment-service
      - net-redis-user-service

  # RabbitMQ condiviso
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - net-rabbitmq-analytics-service
      - net-rabbitmq-auth-service
      - net-rabbitmq-catalog-service
      #- net-rabbitmq-frontend
      - net-rabbitmq-notification-service
      - net-rabbitmq-order-service
      - net-rabbitmq-payment-service
      - net-rabbitmq-user-service
                             
  sql-server:                                             # database MySQL dedicato
    image: mcr.microsoft.com/mssql/server:2019-latest     # immagine MySQL 8.x ufficiale
    container_name: sql-server                            # nome fisso del container DB
    restart: unless-stopped                               # riavvia dopo crash, ma non se fermato a mano
    environment:                                          # credenziali/database da creare al primo avvio
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: rootpass
    volumes:
      - sql-server-data:/var/opt/mssql
    networks:
      - net-sql-server-analytics-service
      - net-sql-server-auth-service
      - net-sql-server-catalog-service
      - net-sql-server-notification-service
      - net-sql-server-order-service
      - net-sql-server-payment-service
      - net-sql-server-user-service

volumes:
  redis_data:
  rabbitmq_data:
  sql-server-data:

networks:
  # redis <-> each service
  net-redis-analytics-service:
  net-redis-api-gateway:
  net-redis-auth-service:
  net-redis-catalog-service:
  #net-redis-frontend:
  net-redis-notification-service:
  net-redis-order-service:
  net-redis-payment-service:
  net-redis-user-service:

  # rabbitmq <-> each service
  net-rabbitmq-analytics-service:
  net-rabbitmq-auth-service:
  net-rabbitmq-catalog-service:
  #net-rabbitmq-frontend:
  net-rabbitmq-notification-service:
  net-rabbitmq-order-service:
  net-rabbitmq-payment-service:
  net-rabbitmq-user-service:
  
  # sql-server <-> each service
  net-sql-server-analytics-service:
  net-sql-server-auth-service:
  net-sql-server-catalog-service:
  net-sql-server-notification-service:
  net-sql-server-order-service:
  net-sql-server-payment-service:
  net-sql-server-user-service:
  
  # api-gateway <-> each service
  net-api-gateway-analytics-service:
  net-api-gateway-auth-service:
  net-api-gateway-catalog-service:
  #net-api-gateway-frontend:
  net-api-gateway-notification-service:
  net-api-gateway-order-service:
  net-api-gateway-payment-service:
  net-api-gateway-user-service: