services:
  api-gateway:
    build:
      context: ./kong-gateway

      dockerfile: Dockerfile

    # image: kong:3.6

    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    # volumes:
    #   - ./kong-gateway/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - internal
    restart: unless-stopped
