services:
  api-gateway:
    build:
      context: ./kong-gateway
      dockerfile: Dockerfile
    image: kong:3.6
    container_name: kong-gateway
    entrypoint: ["/docker-entrypoint-custom.sh"]

    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    volumes:
      - ./kong-gateway/conf.d:/etc/kong/conf.d:ro
      - ./kong-gateway/entrypoint.sh:/docker-entrypoint-custom.sh:ro
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - internal
    restart: unless-stopped