#C:\Repos\Laravel-Microservices\order-service\docker-compose.yml
services:
  order-service:                                    # servizio Laravel “order-service”
    build:                                              # builda un’immagine partendo dal Dockerfile in questa cartella
      context: .
      dockerfile: Dockerfile
    container_name: order-service                   # nome fisso del container
    env_file:
      - ./.env                                          # carica variabili (DB, app key, ecc.) dal file .env locale
    volumes:
      - ./:/var/www/html                                # bind-mount del sorgente: ogni modifica locale si vede subito nel container
    depends_on:                                         # ordine di avvio (non health-check)
      - sql-server                                    
      - redis
      - rabbitmq
    networks:
      - net-api-gateway-order-service
      - net-rabbitmq-order-service
      - net-redis-order-service
      - net-sql-server-order-service                # rete verso il gruppo SQL Server 1

networks:
  net-api-gateway-order-service: { external: true }
  net-rabbitmq-order-service:    { external: true }
  net-redis-order-service:       { external: true }
  net-sql-server-order-service:  { external: true }
