services:
  keycloak-auth-service:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak-auth-service
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - internal
    restart: unless-stopped
