#C:\Repos\Laravel-Microservices\payment-service\docker-compose.yml
services:
  payment-service:                                      # servizio Laravel “payment-service”
    build:                                              # builda un’immagine partendo dal Dockerfile in questa cartella
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service                     # nome fisso del container
    env_file: payment-service/.env                    # carica variabili (DB, app key, ecc.) dal file .env locale
    ports:
      - "8006:80"
    volumes:
      - ./payment-service:/var/www/html                              # bind-mount del sorgente: ogni modifica locale si vede subito nel container
    depends_on:                                         # ordine di avvio (non health-check)
      - sql-server                                    
      - redis
      - rabbitmq
    networks:
      - internal
      # - net-api-gateway-payment-service
      # - net-rabbitmq-payment-service
      # - net-redis-payment-service
      # - net-sql-server-payment-service                  # rete verso il gruppo SQL Server 1

# networks:
#   net-api-gateway-payment-service: { external: true }
#   net-rabbitmq-payment-service:    { external: true }
#   net-redis-payment-service:       { external: true }
#   net-sql-server-payment-service:  { external: true }
