#C:\Repos\Laravel-Microservices\user-service\docker-compose.yml
services:
  user-service:                                         # servizio Laravel “user-service”
    build:                                              # builda un’immagine partendo dal Dockerfile in questa cartella
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service                        # nome fisso del container
    env_file: user-service/.env                       # carica variabili (DB, app key, ecc.) dal file .env locale
    volumes:
      - ./:/var/www/html                                # bind-mount del sorgente: ogni modifica locale si vede subito nel container
    depends_on:                                         # ordine di avvio (non health-check)
      - sql-server                                    
      - redis
      - rabbitmq
    networks:
      - net-api-gateway-user-service
      - net-rabbitmq-user-service
      - net-redis-user-service
      - net-sql-server-user-service                # rete verso il gruppo SQL Server 1

# networks:
#   net-api-gateway-user-service: { external: true }
#   net-rabbitmq-user-service:    { external: true }
#   net-redis-user-service:       { external: true }
#   net-sql-server-user-service:  { external: true }
